<?php
// Liga
$locale['100'] ="Zur Tabelle";
$locale['101'] ="Allgemeine Informationen zur Veranstaltung !";
$locale['102'] ="Veranstaltung";
$locale['103'] ="Regeln";
$locale['104'] ="Beschreibung";
$locale['105'] ="Teilnehmende Teams";

// Tabelle
$locale['110'] ="<b>Bitte eine Veranstaltung auswählen<b>";
$locale['111'] ="Platz";
$locale['112'] ="Fahrer";
$locale['113'] ="Punkte";
$locale['114'] ="Strafpunkte";
$locale['115'] ="Gesamtpunkte";
$locale['116'] ="";
$locale['117'] ="";
$locale['118'] ="";
$locale['119'] ="";
$locale['120'] ="Veranstaltungs Übersicht";

// Renndetails
$locale['121'] ="Renndetails";
$locale['122'] ="Datum";
$locale['123'] ="Rahmenbedingungen";
$locale['124'] ="<b>Rennstrecke</b>";
$locale['125'] ="<b>Runden</b>";
$locale['126'] ="<b>Land</b>";
$locale['127'] ="<b>Teilnehmer</b>";
$locale['128'] ="<b>Status</b>";
$locale['129'] ="Qualifying";
$locale['130'] ="Platz";
$locale['131'] ="Name";
$locale['132'] ="Zeit";
$locale['133'] ="Übersicht der letzten Rennen !";
$locale['134'] ="Übersicht der kommenden Rennen !";
$locale['135'] ="<b>Es existieren keine Informationen zum Qualifying</b>";
$locale['136'] ="<b>Es existieren keine Informationen zum Rennen</b>";
$locale['137'] ="Beschreibung :";
$locale['138'] ="<b>Reglement</b>";
$locale['139'] ="<b>Lizenz</b>";