<?php
/*-------------------------------------------------------+
| PHP-Liga System
| Copyright (C) Com Tec 24
| https://www.com-tec24.de/
+--------------------------------------------------------+
| Filename: Locale.inc
| Author: PHP Liga Development Team
+--------------------------------------------------------+
| 
+--------------------------------------------------------*/

// global $locale ;
$Locale['100'] = "GSR Cannonball";
$locale['101'] = "";
$locale['102'] ="GS Racing";
$locale['103'] = "Copyright 2018 German Street Racing Cannonball &copy;. All Rights Reserved.";
$locale['104'] = "GS Racing ";
$locale['105'] = "Cannonball";
$locale['106'] = "German Street Racing";
$locale['107'] = "pr&auml;sentiert die Cannonball Liga.";


$locale['460'] ="Leer";
$locale['461'] ="Bytes";
$locale['462'] ="KB";
$locale['463'] ="MB";
$locale['464'] ="GB";
$locale['465'] ="TB";

$webmastermail 	= "info@gsrc-racing.de";
$mailname		= "GS Racing© Administrator";

$punkte 		= "Race";


$headerline		= "Wir starten bald";
$headerline		= "Lasst die Motoren warm laufen, es dauert nicht mehr lange.";


?>