<?php
/*-------------------------------------------------------+
 | PHP-Liga System
 | Copyright (C) Com Tec 24
 | https://www.com-tec24.de/
 +--------------------------------------------------------+
 | Filename: menu.inc
 | Author: PHP Liga Development Team
 +--------------------------------------------------------+
 |
 +--------------------------------------------------------*/
//include 'includes/classes/constants_core_include.php';


$locale['100'] ="Neues Mitglied";
$locale['101'] ="Spiele Übersicht";
$locale['102'] ="Rennkalender";
$locale['103'] ="Startseite";
$locale['104'] ="GS Racing";
$locale['105'] ="Pro Street Liga";
$locale['106'] ="";
$locale['107'] ="";
$locale['108'] ="";
$locale['109'] ="";
$locale['110'] ="";
$locale['111'] ="";
$locale['112'] ="";
$locale['113'] ="";



$locale['200'] ="";
$locale['201'] ="";
$locale['202'] ="";
$locale['203'] ="";
$locale['204'] ="";
$locale['205'] ="";
$locale['206'] ="";
$locale['207'] ="";
$locale['208'] ="";
$locale['209'] ="";
$locale['210'] ="";
$locale['211'] ="";
$locale['212'] ="";
$locale['213'] ="";